### ISSUE TITLE
Suggestion: use a chained API

### ISSUE THREAD

**Issue by geelen** [devilcoders/tachyons-for-js#1]
Also known as a "train wreck" api. Your first example would become:

```js
const styles = () => ({
  ...tc.ma3.br2.ttu,
})
```

I've done something similar for styled components, because with string interpolation you can guarantee `toString` gets called eventually. I'm not 100% sure how it would work with `...`, but I _think_ you could define all the functions `ma3`, `br2` and `ttu` as non-enumerable, then each returns the same object with more enumerable keys defined, and it... should just work? Maybe?

Anyway, could save you a bunch of lines once you start to have a ton of these classes.

**Comment by geelen** [comment]
Ok I nerd sniped myself, here's an implementation:

```js
const Definitions = {
  // Entirety of tachyons would go here
  ma3: { margin: '1rem' },
  br2: { borderRadius: '.25rem' },
  ttu: { textTransform: 'uppercase' },
}

// Public API
class ObjectTrainWreck {
  constructor(props) {
    Object.assign(this, props) // these are enumerable, so Object assign will copy them across
    Object.keys(Definitions).forEach(key => {
      Object.defineProperty(this, key, {
        enumerable: false, // these are not enumerable, so they're effectively hidden
        get: () => {
          return new ObjectTrainWreck({
            ...props,
            ...Definitions[key],
          })
        }
      })
    })
  }
}

const tc = new ObjectTrainWreck()

const one_styles = ({
  ...tc.ma3,
  something: 'else'
})

const all_three = ({
  ...tc.ma3.br2.ttu,
  something: 'else'
})

console.log(one_styles)
console.log(all_three)
```

You can [see that running here](http://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=MYewdgzgLgBAIgUwGYEswqi8EYF4YDeAUDDAPRkwCiYmATglAJ4whIxQCGwAFk9jB4IGJGAFtOAZgBchcZzoBzNLIDkARgZjVMAL4AaUQCM6AJlkEYRkHQAmwgEqdbKAK4Q1AOlMBWLToNRKChXCw4EAA8oABU6TkgkGzE1VwAHVOFgTggEAMNdIiIKGAAFVyMAGxRgGABBEoBJImAK7JwAeSMAKwRgGLi0AHUGYABrQlFQSCg6Vz6bAApUuhBUiABKCdJSKYgQCoRPCpBFJZW19dFSTp6-zzaURTAFqB4UCH0YZdWNq5gb3pQTyjBBMCALRCodCYbDrTyJOhUbg8BYgli4AB8W22126gM89ihCBK52EzBebw-MDRn2IOJxCDArjEwk4lQQsiQnAqOUM9O2ikYsgWm0x2P5pAYIToYBgYAQAHd_ni-rFOEMRqMFnSJTjPPrvms-brtvrPJC0BgsJAANpogC6xt1ukuzr-pBdf09HqIBWa2FgUBq-HlSoBqoGYGGvS1l3901Y8oA-tAmAccPhtaIzUHPBJJMa9izXmhFGoEDzcr647tYNyKknXgwEHgYFnSDngHmpJ4TKZPMFXIWQMW3mAyzBVBWcqpq4VdvtDsdTuAECnmOnLguDkcTgt642eM31kA&debug=false&circleciRepo=&evaluate=true&lineWrap=false&presets=react%2Cstage-2&targets=&version=6.26.0), your browser console should output:

```
Object { margin: "1rem", something: "else" }
Object { margin: "1rem", borderRadius: ".25rem", textTransform: "uppercase", something: "else" }
```

**Comment by devilcoders** [comment]
@geelen Nice! I'll take a look. Thanks, it looks great!

**Comment by devilcoders** [comment]
@geelen Just pushed new release with chaining api. Thanks a lot!
